builds:
  - id: exporter
    main: ./cmd/catchpoint-exporter
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: 'exporter'

dockers:
  - id: amd64
    goos: linux
    goarch: amd64
    ids:
      - exporter
    image_templates:
      - "ghcr.io/jsirianni/catchpoint-prometheus-exporter-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    dockerfile: ./Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/amd64"
  - id: arm64
    goos: linux
    goarch: arm64
    ids:
      - exporter
    image_templates:
      - "ghcr.io/jsirianni/catchpoint-prometheus-exporter-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    dockerfile: ./Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/jsirianni/catchpoint-prometheus-exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/jsirianni/catchpoint-prometheus-exporter-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/jsirianni/catchpoint-prometheus-exporter-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"

release:
  draft: false
  prerelease: false
